theme: jekyll-theme-midnight

title: Cypher Eberron
description: site to help run an eberron setting with the cypher system.


collections:
  characters
    output: true
    permalink: /:collection/:name
  rules
    output: true
    permalink: /:collection/:name
